services:
  # Frontend service only
  - type: web
    name: ocr-software-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: "https://ocr-software-62gw.onrender.com"
      - key: REACT_APP_ENV
        value: "production"
      - key: NODE_VERSION
        value: 16.15.0
