## updated

services:
  - type: web
    name: ocr-software-frontend
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: "https://ocr-software-62gw.onrender.com"
      - key: REACT_APP_ENV
        value: "production"
      - key: NODE_VERSION
        value: 18.18.0
